# Copyright (c) 2024 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

name: Auto-merge results
on:
  workflow_run:
    workflows: ["Check Results"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{github.event.workflow_run.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      TRUSTED_AUTHORS: |
        (
          "PerMac"
          "hakehuang"
        )
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug authors
        run: |
          PR_AUTHOR="${{ github.event.workflow_run.user.login }}"
          PR_LABELS="${{ github.event.workflow_run.labels.*.name }}"
          IS_LABEL="${{ contains( github.event.workflow_run.labels.*.name, 'results') }}"
          TRUSTED_AUTHORS = ${{ env.TRUSTED_AUTHORS }}

          echo "Trusted authors ${TRUSTED_AUTHORS}"
          echo "PR author ${PR_AUTHOR}"
          echo "PR labels ${PR_LABELS}"
          echo "IS LABEL ${IS_LABEL}"

          echo "Checking if ${PR_AUTHOR} is a trusted author..."
          AUTHOR_FOUND=0
          for item in ${TRUSTED_AUTHORS[*]}
          do
            if [[ "$item" == ${PR_AUTHOR} ]]
            then
              echo "Found trusted author"
              AUTHOR_FOUND=1
            fi
          done

          if [[ ${AUTHOR_FOUND} == 1 ]]
          then
            echo "enabling auto-merge"
            gh pr merge --auto --rebase "$PR_URL"
          else
            echo "PR's author is not among trusted authors. Auto-merge not enable"
          fi

  on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Results verification failed. No auto-merge."
